### ISSUE TITLE
Difference with ecommerceng

### ISSUE THREAD

**Issue by jbonlinea** [Monogramm/dolibarr-ecommerceext#1]
Hello, 
just a quick question, what is the difference between this repo and the original one(s) you forked ? 
I mean technically, in terms of features, and in terms of project (roadmap)  ?

Bonjour 
petite question rapide ; quelle est la différence entre ce repo et l'original (les originaux) que vous avez forker ?
Je pose la question du point de vu technique, des fonctionnalités et des perspective du projet.

Thank's / Merci !

**Comment by madmath03** [comment]
Hello,

For now, the only difference is that the original repo use the WooCommerce legacy v2 API while this repo uses only the v3 API (see for details [API documentation](https://woocommerce.github.io/woocommerce-rest-api-docs/)).
This only a technical difference, but by doing this it will allow us to use the latest features of WC. For instance, we could use the WC authentication endpoint to automatically generate API keys and ease the setup process, or we could use the WC WebHooks to offer a full synchronization process (Dolibarr -> WC and WC -> Dolibarr).

In terms of roadmap,  because this module is not our top priority, we have no roadmap in mind, only a list of features we want to add.

Apart from the features mentioned above, our next step will be to (re)introduce the Magento synchronization but completely remove the v1 SOAP API and use only the Magento 2 REST API (see [API documentation](https://devdocs.magento.com/redoc/2.3/index.html) for details). This will give a more consistent plugin focused on latest REST API.

Even though we currently do not have much time to dedicate to this module, we gladly appreciate any issues reported or PR submitted 😉 

---

Bonjour,

Pour le moment, la seule différence est que le projet d'origine utilise l'API legacy v2 de WooCommerce, alors que celui-ci utilise uniquement la dernière API v3 (pour plus de détails, reportez-vous à la [documentation de l'API](https://woocommerce.github.io/woocommerce-rest-api-docs/)).
Ce n’est qu’une différence technique, mais cela nous permettra d’utiliser les dernières fonctionnalités de WC. Par exemple, nous pourrions utiliser le endpoint d’authentification WC pour générer automatiquement des clés d’API et faciliter le processus de configuration, ou utiliser les WebHooks WC pour offrir un processus de synchronisation complet (Dolibarr -> WC et WC -> Dolibarr).

En termes de planning, ce module n'étant pas notre priorité, nous n'avons aucun planning en tête, mais seulement une liste de fonctionnalités que nous souhaitons ajouter.

Outre les fonctionnalités mentionnées ci-dessus, notre prochaine étape consistera à (re)introduire la synchronisation Magento mais en supprimant complètement l'API SOAP v1 et n'utiliser que l'API REST Magento 2 (voir [documentation API](https://devdocs.magento.com/redoc/2.3/index.html) pour plus de détails). Cela donnera un plugin plus cohérent axé sur les dernières API REST.

Même si nous n’avons actuellement pas beaucoup de temps à consacrer à ce module, nous apprécions volontiers les tickets signalés ou les Pull Request 😉
